steps:

  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args: ["-c", "./devops/build.sh"]
    env: 
      - 'BRANCH_NAME=$BRANCH_NAME'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'TAG_NAME=$TAG_NAME'